# Generated by Django 5.1.15 on 2026-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacherprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
