import { create } from "zustand";
export const useTestStore = create((set) => ({
    sessionId: null,
    accessToken: null,
    testId: null,
    questions: [],
    durationSeconds: 0,
    enableProctoring: false,
    testType: "mcq",
    currentIndex: 0,
    answers: {},
    timeRemaining: 0,
    status: "idle",
    completionReason: "",
    score: null,
    maxScore: null,
    percentage: null,
    grade: null,
    errorMessage: null,
    wsStatus: "connecting",
    proctoringAlert: null,
    setIdentity: (sessionId, accessToken, testId) => set({ sessionId, accessToken, testId }),
    setStatus: (status) => set({ status }),
    setWsStatus: (wsStatus) => set({ wsStatus }),
    setError: (msg) => set({ status: "error", errorMessage: msg }),
    applySyncState: (data) => set((s) => ({
        questions: data.questions ?? s.questions,
        currentIndex: data.current_index,
        timeRemaining: data.time_remaining,
        durationSeconds: data.duration_seconds,
        answers: Object.fromEntries(Object.entries(data.answers).map(([id, v]) => [id, v.answer])),
        status: data.is_completed ? "completed" : "in_progress",
        completionReason: data.completion_reason,
    })),
    setAnswer: (questionId, answer) => set((s) => ({ answers: { ...s.answers, [questionId]: answer } })),
    setCurrentIndex: (i) => set({ currentIndex: i }),
    tickTimer: (remaining) => set({ timeRemaining: remaining }),
    setCompleted: (reason, score, maxScore, percentage, grade) => set({ status: "completed", completionReason: reason, score, maxScore, percentage, grade }),
    setProctoringAlert: (proctoringAlert) => set({ proctoringAlert }),
}));
