# Generated by Django 5.1.15 on 2026-07-12 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_udisereport'),
        ('tenancy', '0005_tenantconfig_logo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('test_type', models.CharField(choices=[('mcq', 'MCQ'), ('voice', 'Voice'), ('hybrid', 'Hybrid (MCQ + Voice)')], default='mcq', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('passing_percentage', models.FloatField(default=35.0)),
                ('enable_proctoring', models.BooleanField(default=True)),
                ('enable_voice_tts', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('lb_test_id', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_tests', to='academics.academicyear')),
                ('classrooms', models.ManyToManyField(related_name='online_tests', to='academics.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_online_tests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_tests', to='academics.subject')),
            ],
            options={
                'ordering': ['-available_from'],
            },
        ),
        migrations.CreateModel(
            name='StudentTestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('pod_url', models.URLField(blank=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tokens', to='academics.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='assessments.onlinetest')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=4)),
                ('time_taken_seconds', models.PositiveIntegerField()),
                ('completion_reason', models.CharField(choices=[('submitted', 'Submitted'), ('time_expired', 'Time Expired'), ('disconnected', 'Disconnected')], max_length=16)),
                ('answers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='academics.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.onlinetest')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.studenttesttoken')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('looking_away', 'Looking Away'), ('multiple_people', 'Multiple People'), ('phone_detected', 'Phone Detected'), ('tab_switch', 'Tab Switch')], max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='assessments.testresult')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('voice', 'Voice')], default='mcq', max_length=16)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=8)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('voice_grading_hint', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.onlinetest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'order')},
            },
        ),
    ]
