# Generated by Django 5.1.15 on 2026-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_registrationinterest_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schooldomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
