# Generated by Django 5.1.15 on 2026-05-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_student_pending_parent'),
        ('accounts', '0005_otprequest_purpose_password_reset'),
        ('tenancy', '0005_tenantconfig_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissalIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eta_minutes', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.parentprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissal_intents', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
