from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from common.models import SchoolScopedModel, TimestampedModel


class PlatformUser(AbstractUser):
    phone = models.CharField(max_length=20, blank=True)
    is_phone_verified = models.BooleanField(default=False)
    is_email_verified = models.BooleanField(default=False)
    default_school = models.ForeignKey(
        "tenancy.School",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="default_users",
    )


class DeviceSession(TimestampedModel):
    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    device_id = models.CharField(max_length=128)
    platform = models.CharField(max_length=32)
    is_active = models.BooleanField(default=True)


class ParentProfile(SchoolScopedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    google_sub = models.CharField(max_length=128, unique=True, null=True, blank=True)


class TeacherProfile(SchoolScopedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    employee_code = models.CharField(max_length=64, blank=True)
    google_sub = models.CharField(max_length=128, unique=True, null=True, blank=True)
    # JSON blob saved during first-week class-selection onboarding.
    # Schema: {"classroomIds": [1, 2], "setupCompleted": true, "setupCompletedAt": "2026-04-17"}
    # Once setupCompleted is true, the backend auto-generates ClassSession records
    # from classroomIds and uses them as the teacher's recurring weekly schedule.
    schedule_preferences = models.JSONField(default=dict, blank=True)


class TeacherInvitation(TimestampedModel):
    """An invite token generated by the admin dashboard and sent to a teacher's email.

    The teacher opens the link (deep-link or manual token entry), registers their
    account, and goes through first-week class-selection onboarding.  Once used,
    is_used is set to True and the token cannot be reused.
    """

    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    email = models.EmailField()
    token = models.CharField(max_length=128, unique=True)
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    is_used = models.BooleanField(default=False)


class DriverProfile(SchoolScopedModel):
    """Driver identity record.

    Phone number is the primary auth credential (OTP-based login).
    A driver is uniquely identified across multiple vehicle assignments
    by their aadhar_number.  Multiple vehicles can be assigned to the
    same driver/aadhar; each assignment can carry its own contact phone.
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Primary auth / contact phone — used for OTP login
    phone = models.CharField(max_length=20)
    # Aadhaar links the driver identity across multiple vehicle assignments
    aadhar_number = models.CharField(max_length=20, blank=True)
    otp_multi_device_limit = models.PositiveSmallIntegerField(default=2)
    # is_approved is False for self-signup drivers until an admin approves them
    is_approved = models.BooleanField(default=True)


class DriverInvitation(TimestampedModel):
    """An invite token generated by the admin dashboard and sent to a driver.

    Invited drivers bypass the approval queue — they are immediately active
    once they complete signup.  Self-signup drivers (no invite) go through
    the DriverSignupRequest queue instead.
    """

    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    token = models.CharField(max_length=128, unique=True)
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    is_used = models.BooleanField(default=False)


class OTPRequest(TimestampedModel):
    """A one-time password request for passwordless login or action confirmation.

    Used by:
    - Parents and drivers logging in via phone/email OTP
    - Parents confirming a destructive action (e.g. removing student from bus)

    The raw code is never stored; only its SHA-256 hash is persisted so a DB
    breach cannot reveal valid codes.  Max 5 verify attempts before the record
    is voided to prevent brute-force.
    """

    class Channel(models.TextChoices):
        SMS = "sms", "SMS"
        EMAIL = "email", "Email"

    class Role(models.TextChoices):
        PARENT  = "parent",  "Parent"
        DRIVER  = "driver",  "Driver"
        TEACHER = "teacher", "Teacher"
        ADMIN   = "admin",   "Admin"

    class Purpose(models.TextChoices):
        LOGIN = "login", "Login"
        CONFIRM_ACTION = "confirm_action", "Confirm Action"
        PASSWORD_RESET = "password_reset", "Password Reset"

    school = models.ForeignKey("tenancy.School", null=True, blank=True, on_delete=models.SET_NULL)
    contact = models.CharField(max_length=255)  # phone number or email address
    channel = models.CharField(max_length=8, choices=Channel.choices)
    role = models.CharField(max_length=16, choices=Role.choices)
    purpose = models.CharField(max_length=20, choices=Purpose.choices, default=Purpose.LOGIN)
    code_hash = models.CharField(max_length=64)  # SHA-256 hex digest of the 6-digit code
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    attempts = models.PositiveSmallIntegerField(default=0)
    context = models.JSONField(default=dict, blank=True)  # e.g. {"student_id": 5} for action OTPs


# ── Role-Based Access Control ─────────────────────────────────────────────────

ALL_PERMISSIONS = [
    ("manage_students",     "Manage Students"),
    ("view_students",       "View Students"),
    ("manage_fees",         "Manage Fees"),
    ("collect_fees",        "Collect Fees"),
    ("view_fees",           "View Fees"),
    ("manage_attendance",   "Manage Attendance"),
    ("view_attendance",     "View Attendance"),
    ("manage_timetable",    "Manage Timetable"),
    ("manage_staff",        "Manage Staff"),
    ("view_staff",          "View Staff"),
    ("manage_exams",        "Manage Exams"),
    ("enter_marks",         "Enter Marks"),
    ("send_communications", "Send Communications"),
    ("view_reports",        "View Reports"),
    ("manage_settings",     "Manage Settings"),
]

PERMISSION_CODES = [code for code, _ in ALL_PERMISSIONS]


class SchoolRole(SchoolScopedModel):
    """A named role with a set of permission codes, scoped to one school."""
    name = models.CharField(max_length=64)
    permissions = models.JSONField(default=list)   # list of permission code strings
    is_system = models.BooleanField(default=False)  # built-in roles cannot be deleted

    class Meta:
        unique_together = [("school", "name")]
        ordering = ["name"]


class UserSchoolRole(TimestampedModel):
    """Assigns a SchoolRole to a PlatformUser within a school."""
    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="school_roles")
    role = models.ForeignKey(SchoolRole, on_delete=models.CASCADE, related_name="assignments")
    assigned_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="role_assignments_made")

    class Meta:
        unique_together = [("user", "role")]


class DriverSignupRequest(TimestampedModel):
    """A self-initiated driver signup request that requires admin approval.

    The driver selects a school from a list, fills in their details, and waits
    for the admin dashboard to approve them.  Once approved, a DriverProfile is
    created and the driver can log in normally.
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"

    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    aadhar_number = models.CharField(max_length=20, blank=True)
    vehicle_registration = models.CharField(max_length=32, blank=True)
    status = models.CharField(max_length=32, choices=Status.choices, default=Status.PENDING)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )


# ── Teacher Leave & Substitute Management ─────────────────────────────────────

class TeacherLeave(SchoolScopedModel):
    """A leave request by or for a teacher, managed by admin."""

    class Status(models.TextChoices):
        PENDING  = "pending",  "Pending"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"

    class LeaveType(models.TextChoices):
        SICK    = "sick",    "Sick"
        CASUAL  = "casual",  "Casual"
        OTHER   = "other",   "Other"

    teacher    = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, related_name="leaves")
    leave_type = models.CharField(max_length=16, choices=LeaveType.choices, default=LeaveType.CASUAL)
    start_date = models.DateField()
    end_date   = models.DateField()
    reason     = models.TextField(blank=True)
    status     = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="approved_leaves",
    )
    admin_note = models.TextField(blank=True)

    class Meta:
        ordering = ["-start_date"]


class SubstituteAssignment(SchoolScopedModel):
    """Records which teacher is covering a specific slot on a specific date
    for a teacher who is on leave."""

    leave        = models.ForeignKey(TeacherLeave, on_delete=models.CASCADE, related_name="substitutes")
    date         = models.DateField()
    # Optionally linked to the exact timetable slot being covered
    timetable_slot = models.ForeignKey(
        "academics.TimetableSlot", null=True, blank=True,
        on_delete=models.SET_NULL, related_name="substitute_assignments",
    )
    period_label = models.CharField(max_length=128, blank=True)  # e.g. "Period 2 – Maths (09:00–09:45)"
    substitute   = models.ForeignKey(
        TeacherProfile, on_delete=models.CASCADE, related_name="substitute_assignments",
    )
    assigned_by  = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        ordering = ["date"]
        unique_together = [("leave", "date", "timetable_slot")]
