from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from common.models import SchoolScopedModel, TimestampedModel


class PlatformUser(AbstractUser):
    phone = models.CharField(max_length=20, blank=True)
    is_phone_verified = models.BooleanField(default=False)
    default_school = models.ForeignKey(
        "tenancy.School",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="default_users",
    )


class DeviceSession(TimestampedModel):
    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    device_id = models.CharField(max_length=128)
    platform = models.CharField(max_length=32)
    is_active = models.BooleanField(default=True)


class ParentProfile(SchoolScopedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)


class TeacherProfile(SchoolScopedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    employee_code = models.CharField(max_length=64, blank=True)
    # JSON blob saved during first-week class-selection onboarding.
    # Schema: {"classroomIds": [1, 2], "setupCompleted": true, "setupCompletedAt": "2026-04-17"}
    # Once setupCompleted is true, the backend auto-generates ClassSession records
    # from classroomIds and uses them as the teacher's recurring weekly schedule.
    schedule_preferences = models.JSONField(default=dict, blank=True)


class TeacherInvitation(TimestampedModel):
    """An invite token generated by the admin dashboard and sent to a teacher's email.

    The teacher opens the link (deep-link or manual token entry), registers their
    account, and goes through first-week class-selection onboarding.  Once used,
    is_used is set to True and the token cannot be reused.
    """

    school = models.ForeignKey("tenancy.School", on_delete=models.CASCADE)
    email = models.EmailField()
    token = models.CharField(max_length=128, unique=True)
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    is_used = models.BooleanField(default=False)


class DriverProfile(SchoolScopedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    otp_multi_device_limit = models.PositiveSmallIntegerField(default=2)
