import hashlib
import random
import secrets
import string
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.utils import timezone
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken

from apps.accounts.models import DriverProfile, OTPRequest, ParentProfile
from apps.tenancy.models import School
from common.demo_state import (
    accept_driver_invite,
    accept_invite,
    login_payload,
    submit_driver_self_signup,
    validate_driver_invite,
    validate_invite,
)
from common.sms import send_sms
from integrations.email_service import send_otp_email

User = get_user_model()

_OTP_TTL_MINUTES = 10
_OTP_MAX_ATTEMPTS = 5


def _generate_otp() -> str:
    return "".join(random.choices(string.digits, k=6))


def _hash_code(code: str) -> str:
    return hashlib.sha256(code.encode()).hexdigest()


def _jwt_for_user(user) -> dict:
    refresh = RefreshToken.for_user(user)
    return {"refresh": str(refresh), "access": str(refresh.access_token)}


class AdminLoginView(APIView):
    """Email + password login for staff and superusers. Returns JWT tokens."""

    authentication_classes = []
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        email = (request.data.get("email") or "").strip().lower()
        password = request.data.get("password", "")
        if not email or not password:
            return Response({"detail": "email and password are required."}, status=400)

        # Prefer superuser > staff when duplicates exist (data-level deduplication pending)
        user = (
            User.objects
            .filter(email__iexact=email)
            .order_by("-is_superuser", "-is_staff", "id")
            .first()
        )
        if user is None:
            return Response({"detail": "Invalid credentials."}, status=401)

        if not user.check_password(password):
            return Response({"detail": "Invalid credentials."}, status=401)

        if not user.is_staff:
            return Response({"detail": "Access denied. Staff only."}, status=403)

        tokens = _jwt_for_user(user)
        return Response({
            **tokens,
            "role": "superuser" if user.is_superuser else "staff",
            "name": user.get_full_name() or user.email,
            "email": user.email,
            "id": user.id,
        })


class AccountsRootView(APIView):
    """Liveness probe for the accounts module."""

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        return Response({"module": "accounts", "status": "ready", "mode": "demo"})


class DemoLoginView(APIView):
    """Demo login – returns a hard-coded payload for the given role.

    POST body:
        role (str) – one of parent | driver | teacher.
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        role = request.data.get("role")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role), status=status.HTTP_200_OK)


class MeView(APIView):
    """Return the current user's login payload (demo version, role from query param)."""

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        role = request.query_params.get("role", "parent")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role))


# ── Teacher invite flow ───────────────────────────────────────────────────────

class ValidateInviteView(APIView):
    """Validate a teacher invite token generated by the admin dashboard.

    GET /api/auth/teacher/invite/{token}/
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request, token: str):
        invite = validate_invite(token)
        if invite is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(invite, status=status.HTTP_200_OK)


class AcceptInviteView(APIView):
    """Complete teacher signup via an invite token.

    POST /api/auth/teacher/accept-invite/
    Body: { "token": "...", "name": "...", "phone": "..." }
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        token = request.data.get("token", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()

        if not token or not name or not phone:
            return Response(
                {"detail": "token, name, and phone are all required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = accept_invite(token, name=name, phone=phone)
        if payload is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(payload, status=status.HTTP_201_CREATED)


# ── Driver invite flow (req 6) ────────────────────────────────────────────────

class ValidateDriverInviteView(APIView):
    """Validate a driver invite token generated by the admin dashboard (req 6).

    Invited drivers are immediately active after completing signup — they don't
    need to wait for admin approval.

    GET /api/auth/driver/invite/{token}/
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request, token: str):
        invite = validate_driver_invite(token)
        if invite is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(invite, status=status.HTTP_200_OK)


class AcceptDriverInviteView(APIView):
    """Complete driver signup via an admin invite token (req 6).

    Returns a full login payload without an approval requirement.

    POST /api/auth/driver/accept-invite/
    Body: { "token": "...", "name": "...", "phone": "...", "aadhar": "..." }
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        token = request.data.get("token", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()
        aadhar = request.data.get("aadhar", "").strip()

        if not token or not name or not phone:
            return Response(
                {"detail": "token, name, and phone are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = accept_driver_invite(token, name=name, phone=phone, aadhar=aadhar)
        if payload is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(payload, status=status.HTTP_201_CREATED)


# ── OTP login (parent & driver) ───────────────────────────────────────────────

class OTPRequestView(APIView):
    """Send a 6-digit OTP to the parent/driver's phone via SMS or email.

    POST /api/auth/otp/request/
    Body:
        contact     (str) – phone number or email address
        channel     (str) – "sms" or "email"
        role        (str) – "parent" or "driver"
        school_slug (str) – school identifier
        purpose     (str, optional) – "login" (default) or "confirm_action"
        context     (obj, optional) – extra payload stored on the OTP record
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        import logging
        log = logging.getLogger(__name__)

        contact = request.data.get("contact", "").strip()
        channel = request.data.get("channel", "sms")
        role = request.data.get("role", "")
        school_slug = request.data.get("school_slug", "").strip()
        purpose = request.data.get("purpose", OTPRequest.Purpose.LOGIN)
        context = request.data.get("context", {})

        if not contact or role not in ("parent", "driver", "admin") or not school_slug:
            return Response(
                {"detail": "contact, role, and school_slug are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        if channel not in ("sms", "email"):
            return Response(
                {"detail": "channel must be 'sms' or 'email'."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            school = School.objects.get(slug=school_slug, is_active=True)
        except School.DoesNotExist:
            return Response({"detail": "School not found."}, status=status.HTTP_404_NOT_FOUND)

        # Verify the contact exists for the given role + school
        fallback_email = None  # used for SMS→email fallback
        if role == "admin":
            user = (
                User.objects
                .filter(email__iexact=contact, default_school=school)
                .first()
            )
            if user is None:
                return Response(
                    {"detail": "No admin account found for this email at the given school."},
                    status=status.HTTP_404_NOT_FOUND,
                )
        elif role == "parent":
            profile = ParentProfile.objects.filter(school=school, phone=contact).select_related("user").first()
            if profile is None:
                return Response(
                    {"detail": "No account found for this contact at the given school."},
                    status=status.HTTP_404_NOT_FOUND,
                )
            fallback_email = profile.user.email or None
        else:  # driver
            profile = DriverProfile.objects.filter(school=school, phone=contact).select_related("user").first()
            if profile is None:
                return Response(
                    {"detail": "No account found for this contact at the given school."},
                    status=status.HTTP_404_NOT_FOUND,
                )
            fallback_email = profile.user.email or None

        code = _generate_otp()
        OTPRequest.objects.create(
            school=school,
            contact=contact,
            channel=channel,
            role=role,
            purpose=purpose,
            code_hash=_hash_code(code),
            expires_at=timezone.now() + timedelta(minutes=_OTP_TTL_MINUTES),
            context=context if isinstance(context, dict) else {},
        )

        if channel == "email" or role == "admin":
            # For admin the contact IS the email; for email channel contact is the email address.
            send_otp_email(to=contact, code=code, ttl_minutes=_OTP_TTL_MINUTES, school_name=school.name)
        else:
            # SMS channel — try MSG91, fall back to email if it fails
            sms_ok = send_sms(to=contact, message=f"Your Skippo OTP is {code}. Valid for {_OTP_TTL_MINUTES} minutes.")
            if not sms_ok:
                log.warning("SMS failed for %s; attempting email fallback", contact)
                if fallback_email:
                    send_otp_email(to=fallback_email, code=code, ttl_minutes=_OTP_TTL_MINUTES, school_name=school.name)
                else:
                    log.warning("No fallback email found for contact %s", contact)

        return Response({"detail": "OTP sent."}, status=status.HTTP_200_OK)


class OTPVerifyView(APIView):
    """Verify an OTP and return JWT tokens on success.

    POST /api/auth/otp/verify/
    Body:
        contact     (str)
        code        (str) – the 6-digit OTP
        role        (str)
        school_slug (str)
        purpose     (str, optional) – must match what was requested

    Returns on login purpose:
        { "access": "...", "refresh": "...", "role": "parent"|"driver" }

    Returns on confirm_action purpose:
        { "confirmed": true }
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        contact = request.data.get("contact", "").strip()
        code = request.data.get("code", "").strip()
        role = request.data.get("role", "")
        school_slug = request.data.get("school_slug", "").strip()
        purpose = request.data.get("purpose", OTPRequest.Purpose.LOGIN)

        if not contact or not code or role not in ("parent", "driver", "admin") or not school_slug:
            return Response(
                {"detail": "contact, code, role, and school_slug are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            school = School.objects.get(slug=school_slug)
        except School.DoesNotExist:
            return Response({"detail": "School not found."}, status=status.HTTP_404_NOT_FOUND)

        otp = (
            OTPRequest.objects.filter(
                school=school,
                contact=contact,
                role=role,
                purpose=purpose,
                is_used=False,
                expires_at__gt=timezone.now(),
                attempts__lt=_OTP_MAX_ATTEMPTS,
            )
            .order_by("-created_at")
            .first()
        )

        if otp is None:
            return Response(
                {"detail": "No valid OTP found. Please request a new one."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if otp.code_hash != _hash_code(code):
            otp.attempts += 1
            otp.save(update_fields=["attempts"])
            remaining = _OTP_MAX_ATTEMPTS - otp.attempts
            return Response(
                {"detail": f"Incorrect code. {remaining} attempt(s) remaining."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        otp.is_used = True
        otp.save(update_fields=["is_used"])

        if purpose == OTPRequest.Purpose.CONFIRM_ACTION:
            return Response({"confirmed": True, "context": otp.context})

        # Login purpose — look up the profile and return JWT tokens
        if role == "admin":
            user = User.objects.filter(email__iexact=contact, default_school=school).first()
            if user is None:
                return Response({"detail": "Profile not found."}, status=status.HTTP_404_NOT_FOUND)
        elif role == "parent":
            try:
                profile = ParentProfile.objects.select_related("user").get(school=school, phone=contact)
            except ParentProfile.DoesNotExist:
                return Response({"detail": "Profile not found."}, status=status.HTTP_404_NOT_FOUND)
            user = profile.user
        else:
            try:
                profile = DriverProfile.objects.select_related("user").get(school=school, phone=contact)
            except DriverProfile.DoesNotExist:
                return Response({"detail": "Profile not found."}, status=status.HTTP_404_NOT_FOUND)
            if not profile.is_approved:
                return Response(
                    {"detail": "Your account is pending approval."},
                    status=status.HTTP_403_FORBIDDEN,
                )
            user = profile.user

        tokens = _jwt_for_user(user)
        return Response({**tokens, "role": role, "user": {"id": user.id, "name": user.get_full_name()}})


class DriverSelfSignupView(APIView):
    """Self-signup for a driver without an admin invite (req 6).

    The driver selects their school from a list and submits their details.
    A pending approval record is created and the driver sees a 'Pending Approval'
    screen in the app until an admin approves them from the dashboard.

    POST /api/auth/driver/signup/
    Body:
        schoolSlug   (str, required) – slug of the school the driver wants to join
        name         (str, required) – driver's full name
        phone        (str, required) – phone number (used for OTP login)
        aadhar       (str, optional) – Aadhaar number linking multiple vehicles
        vehicleReg   (str, optional) – vehicle registration number
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        school_slug = request.data.get("schoolSlug", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()
        aadhar = request.data.get("aadhar", "").strip()
        vehicle_reg = request.data.get("vehicleReg", "").strip()

        if not school_slug or not name or not phone:
            return Response(
                {"detail": "schoolSlug, name, and phone are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = submit_driver_self_signup(
            school_slug=school_slug,
            name=name,
            phone=phone,
            aadhar=aadhar,
            vehicle_reg=vehicle_reg,
        )
        return Response(payload, status=status.HTTP_201_CREATED)
