from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from common.demo_state import accept_invite, login_payload, validate_invite


class AccountsRootView(APIView):
    """Liveness probe for the accounts module."""

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        return Response({"module": "accounts", "status": "ready", "mode": "demo"})


class DemoLoginView(APIView):
    """Demo login – returns a hard-coded payload for the given role.

    POST body:
        role (str) – one of parent | driver | teacher.
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        role = request.data.get("role")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role), status=status.HTTP_200_OK)


class MeView(APIView):
    """Return the current user's login payload (demo version, role from query param).

    Query params:
        role (str) – one of parent | driver | teacher.
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        role = request.query_params.get("role", "parent")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role))


# ── Teacher invite flow ───────────────────────────────────────────────────────

class ValidateInviteView(APIView):
    """Validate a teacher invite token generated by the admin dashboard.

    Returns invite metadata (email, school name) if the token is valid so the
    signup screen can prefill context before the teacher completes registration.

    URL param:
        token (str) – the invite token from the email link.
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request, token: str):
        invite = validate_invite(token)
        if invite is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(invite, status=status.HTTP_200_OK)


class AcceptInviteView(APIView):
    """Complete teacher signup via an invite token.

    Marks the invite as used, creates the teacher account, and returns a login
    payload flagged with is_first_week=True so the app shows the first-week
    class-selection onboarding screen.

    POST body:
        token (str, required) – the invite token from the email link.
        name  (str, required) – teacher's full name.
        phone (str, required) – teacher's phone number for OTP login.
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        token = request.data.get("token", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()

        if not token or not name or not phone:
            return Response(
                {"detail": "token, name, and phone are all required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = accept_invite(token, name=name, phone=phone)
        if payload is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(payload, status=status.HTTP_201_CREATED)
