from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from common.demo_state import (
    accept_driver_invite,
    accept_invite,
    login_payload,
    submit_driver_self_signup,
    validate_driver_invite,
    validate_invite,
)


class AccountsRootView(APIView):
    """Liveness probe for the accounts module."""

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        return Response({"module": "accounts", "status": "ready", "mode": "demo"})


class DemoLoginView(APIView):
    """Demo login – returns a hard-coded payload for the given role.

    POST body:
        role (str) – one of parent | driver | teacher.
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        role = request.data.get("role")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role), status=status.HTTP_200_OK)


class MeView(APIView):
    """Return the current user's login payload (demo version, role from query param)."""

    permission_classes = [permissions.AllowAny]

    def get(self, request):
        role = request.query_params.get("role", "parent")
        if role not in {"parent", "driver", "teacher"}:
            return Response({"detail": "Unsupported role."}, status=status.HTTP_400_BAD_REQUEST)
        return Response(login_payload(role))


# ── Teacher invite flow ───────────────────────────────────────────────────────

class ValidateInviteView(APIView):
    """Validate a teacher invite token generated by the admin dashboard.

    GET /api/auth/teacher/invite/{token}/
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request, token: str):
        invite = validate_invite(token)
        if invite is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(invite, status=status.HTTP_200_OK)


class AcceptInviteView(APIView):
    """Complete teacher signup via an invite token.

    POST /api/auth/teacher/accept-invite/
    Body: { "token": "...", "name": "...", "phone": "..." }
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        token = request.data.get("token", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()

        if not token or not name or not phone:
            return Response(
                {"detail": "token, name, and phone are all required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = accept_invite(token, name=name, phone=phone)
        if payload is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(payload, status=status.HTTP_201_CREATED)


# ── Driver invite flow (req 6) ────────────────────────────────────────────────

class ValidateDriverInviteView(APIView):
    """Validate a driver invite token generated by the admin dashboard (req 6).

    Invited drivers are immediately active after completing signup — they don't
    need to wait for admin approval.

    GET /api/auth/driver/invite/{token}/
    """

    permission_classes = [permissions.AllowAny]

    def get(self, request, token: str):
        invite = validate_driver_invite(token)
        if invite is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(invite, status=status.HTTP_200_OK)


class AcceptDriverInviteView(APIView):
    """Complete driver signup via an admin invite token (req 6).

    Returns a full login payload without an approval requirement.

    POST /api/auth/driver/accept-invite/
    Body: { "token": "...", "name": "...", "phone": "...", "aadhar": "..." }
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        token = request.data.get("token", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()
        aadhar = request.data.get("aadhar", "").strip()

        if not token or not name or not phone:
            return Response(
                {"detail": "token, name, and phone are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = accept_driver_invite(token, name=name, phone=phone, aadhar=aadhar)
        if payload is None:
            return Response(
                {"detail": "Invite not found or already used."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(payload, status=status.HTTP_201_CREATED)


class DriverSelfSignupView(APIView):
    """Self-signup for a driver without an admin invite (req 6).

    The driver selects their school from a list and submits their details.
    A pending approval record is created and the driver sees a 'Pending Approval'
    screen in the app until an admin approves them from the dashboard.

    POST /api/auth/driver/signup/
    Body:
        schoolSlug   (str, required) – slug of the school the driver wants to join
        name         (str, required) – driver's full name
        phone        (str, required) – phone number (used for OTP login)
        aadhar       (str, optional) – Aadhaar number linking multiple vehicles
        vehicleReg   (str, optional) – vehicle registration number
    """

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        school_slug = request.data.get("schoolSlug", "").strip()
        name = request.data.get("name", "").strip()
        phone = request.data.get("phone", "").strip()
        aadhar = request.data.get("aadhar", "").strip()
        vehicle_reg = request.data.get("vehicleReg", "").strip()

        if not school_slug or not name or not phone:
            return Response(
                {"detail": "schoolSlug, name, and phone are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payload = submit_driver_self_signup(
            school_slug=school_slug,
            name=name,
            phone=phone,
            aadhar=aadhar,
            vehicle_reg=vehicle_reg,
        )
        return Response(payload, status=status.HTTP_201_CREATED)
