# Generated by Django 5.1.15 on 2026-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPodRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('test_id', models.CharField(db_index=True, max_length=255)),
                ('pod_url', models.TextField(blank=True)),
                ('machine_state', models.CharField(choices=[('starting', 'Starting'), ('started', 'Started'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('destroyed', 'Destroyed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('allocation_status', models.CharField(choices=[('allocated', 'Allocated'), ('released', 'Released')], db_index=True, default='allocated', max_length=32)),
                ('active_sessions', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('machine_created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_pod_registry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['test_id', 'allocation_status'], name='exam_pod_re_test_id_cc02aa_idx'), models.Index(fields=['machine_state', 'deleted_at'], name='exam_pod_re_machine_a5b842_idx')],
            },
        ),
    ]
