from __future__ import annotations

from copy import deepcopy

# ---------------------------------------------------------------------------
# Demo in-memory state
#
# All backend views run in demo mode — no database queries are made.
# This module owns the single mutable STATE dict that simulates a real school's
# data.  Every view function reads/writes this dict via the helpers below.
#
# Sections of STATE:
#   users           – login payloads keyed by role
#   student/trip/vehicle/students/renewals/devices  – driver + parent domains
#   messages/alerts/progress/dailyReports           – parent feed domain
#   schedule/roster/teacherDailyPreview             – teacher attendance domain
#   classrooms      – full list of classrooms for the class-picker feature
#   broadcasts      – class-wide broadcast messages sent by teachers
#   assistRequests  – parent-raised doubt/help cards per student
#   teacherInvites  – invite tokens generated by admin dashboard
#   schedulePreferences – teacher's saved weekly schedule (first-week setup)
#   sosEvents       – SOS events from driver app
# ---------------------------------------------------------------------------


def _base_state() -> dict:
    return {
        # ── Auth payloads ────────────────────────────────────────────────────
        "users": {
            "parent": {
                "role": "parent",
                "token": "demo-parent-token",
                "name": "Aarav's Parent",
                "school_slug": "greenfield-public-school",
            },
            "driver": {
                "role": "driver",
                "token": "demo-driver-token",
                "name": "Rohit Kumar",
                "school_slug": "greenfield-public-school",
            },
            "teacher": {
                "role": "teacher",
                "token": "demo-teacher-token",
                "name": "Ms. Sen",
                "school_slug": "greenfield-public-school",
                # is_first_week drives the first-week class-selection onboarding
                # flow in the teacher app.  Set to False once the teacher has
                # saved their schedule_preferences.
                "is_first_week": True,
            },
        },

        # ── Parent / student domain ──────────────────────────────────────────
        "student": {
            "id": 1,
            "name": "Aarav Roy",
            "grade": "Class 4B",
            "routeName": "North Route A",
            "stopName": "Lakeview Stop",
        },
        "trip": {
            "id": 201,
            "routeName": "North Route A",
            "busLabel": "Bus 12",
            "vehicleLabel": "Bus 12",
            "shift": "morning",
            "status": "scheduled",
            "tripState": "scheduled",
            "etaMinutes": 8,
            "boardedCount": 1,
            "totalCount": 4,
            "nextStop": "Lakeview Stop",
            "busLocation": {
                "latitude": 22.5726,
                "longitude": 88.3639,
                "speed": 24,
                "heading": 140,
                "updatedAt": "2026-04-13T10:15:00+05:30",
            },
        },
        "vehicle": {
            "id": 1,
            "registrationNumber": "WB-04-AB-1288",
            "label": "Bus 12",
            "routeName": "North Route A",
            "capacity": 42,
        },
        "students": [
            {"id": 1, "name": "Aarav Roy",  "stopName": "Lakeview Stop", "status": "boarded"},
            {"id": 2, "name": "Mira Dutta", "stopName": "Pine Street",   "status": "boarded"},
            {"id": 3, "name": "Ved Singh",  "stopName": "Metro Corner",  "status": "dropped"},
            {"id": 4, "name": "Sia Das",    "stopName": "City Center",   "status": "absent"},
        ],
        "renewals": [
            {"id": 1, "title": "Vehicle fitness certificate", "expiresOn": "2026-04-20", "priority": "urgent"},
            {"id": 2, "title": "Pollution certificate",       "expiresOn": "2026-05-07", "priority": "normal"},
            {"id": 3, "title": "Insurance renewal",           "expiresOn": "2026-05-15", "priority": "normal"},
        ],
        "devices": [
            {"id": 1, "label": "Samsung A54",          "platform": "Android", "isCurrent": True},
            {"id": 2, "label": "School Backup Phone",  "platform": "Android", "isCurrent": False},
        ],
        "messages": [
            {
                "id": 1,
                "title": "Summer activity registrations open",
                "body": "Parents can now enroll students in the school summer activity camp from the message center.",
                "tag": "Update",
                "createdAt": "2026-04-12T09:30:00+05:30",
                "isRead": False,
            },
            {
                "id": 2,
                "title": "Partner offer: school supplies",
                "body": "Discounted notebooks and art kits are available this week through the school partner store.",
                "tag": "Offer",
                "createdAt": "2026-04-10T12:00:00+05:30",
                "isRead": True,
            },
        ],
        "alerts": [
            {
                "id": 1,
                "title": "Bus is 2 stops away",
                "body": "Bus 12 is approaching Lakeview Stop.",
                "level": "info",
                "createdAt": "2026-04-13T10:10:00+05:30",
            },
            {
                "id": 2,
                "title": "Student boarded safely",
                "body": "Aarav boarded Bus 12 at 7:42 AM.",
                "level": "info",
                "createdAt": "2026-04-13T07:42:00+05:30",
            },
        ],
        "progress": [
            {
                "id": 1,
                "student_id": 1,
                "title": "Strong reading progress",
                "note": "Completed the weekly reading task confidently and helped peers during discussion.",
                "category": "Academic",
                "createdAt": "2026-04-12T14:00:00+05:30",
                "isReadByParent": False,
            },
            {
                "id": 2,
                "student_id": 1,
                "title": "Great class participation",
                "note": "Volunteered answers in science and stayed engaged through the full session.",
                "category": "Participation",
                "createdAt": "2026-04-11T11:30:00+05:30",
                "isReadByParent": True,
            },
        ],
        "dailyReports": [
            {
                "id": 1,
                "date": "2026-04-13",
                "attendanceSummary": "Present across all scheduled classes.",
                "teacherCommentSummary": "2 teacher notes were added today.",
                "unreadCommentCount": 1,
            }
        ],

        # ── Teacher / classroom domain ───────────────────────────────────────
        "schedule": [
            {
                "id": 1,
                "classroomLabel": "Class 4B",
                "title": "Morning Attendance",
                "startsAt": "08:00",
                "endsAt": "08:30",
                "isCurrent": True,
                "attendanceBoundary": "school_entry",
            },
            {
                "id": 2,
                "classroomLabel": "Class 4B",
                "title": "Science",
                "startsAt": "10:00",
                "endsAt": "10:45",
                "isCurrent": False,
                "attendanceBoundary": "none",
            },
            {
                "id": 3,
                "classroomLabel": "Class 4B",
                "title": "Closing Period",
                "startsAt": "14:45",
                "endsAt": "15:10",
                "isCurrent": False,
                "attendanceBoundary": "school_exit",
            },
        ],
        "roster": [
            {"id": 1, "fullName": "Aarav Roy",    "rollNumber": "04", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 2, "fullName": "Mira Dutta",   "rollNumber": "07", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 3, "fullName": "Ved Singh",    "rollNumber": "11", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 4, "fullName": "Sia Das",      "rollNumber": "18", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 5, "fullName": "Rohan Mehta",  "rollNumber": "22", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 6, "fullName": "Priya Sharma", "rollNumber": "25", "isPresent": False, "isAbsent": False, "latestComment": ""},
        ],
        "teacherDailyPreview": [
            {
                "studentName": "Aarav Roy",
                "unreadCommentCount": 1,
                "summary": "Present across the day. Two teacher comments; one still unread by parent.",
            },
            {
                "studentName": "Mira Dutta",
                "unreadCommentCount": 0,
                "summary": "Present across the day. No unread teacher comments remaining.",
            },
        ],

        # ── Classrooms list – used by the class-picker feature ───────────────
        # Teachers can manually select a different classroom when verbally
        # assigned to a class outside their scheduled sessions.
        "classrooms": [
            {"id": 1, "name": "Class 4", "section": "B", "label": "Class 4B"},
            {"id": 2, "name": "Class 5", "section": "A", "label": "Class 5A"},
            {"id": 3, "name": "Class 3", "section": "C", "label": "Class 3C"},
            {"id": 4, "name": "Class 6", "section": "A", "label": "Class 6A"},
            {"id": 5, "name": "Class 7", "section": "B", "label": "Class 7B"},
            {"id": 6, "name": "Class 2", "section": "A", "label": "Class 2A"},
        ],

        # ── Class-wide broadcasts sent by the teacher ────────────────────────
        # A broadcast goes to all parents of students in the session's classroom.
        # Stored with the session_id so the teacher can view history per class.
        "broadcasts": [],

        # ── Assist requests raised by parents ────────────────────────────────
        # Parents can raise a doubt/question card from the parent app.  Teachers
        # see these requests inside each student's card on the Attendance screen
        # and can mark them resolved with an optional reply.
        "assistRequests": [
            {
                "id": 1,
                "student_id": 1,
                "student_name": "Aarav Roy",
                "session_id": 1,
                "question": "Could you clarify the fractions homework from yesterday? Aarav got confused and we weren't able to help at home.",
                "status": "pending",
                "teacher_reply": "",
                "raised_at": "2026-04-13T07:45:00+05:30",
                "resolved_at": None,
            },
            {
                "id": 2,
                "student_id": 3,
                "student_name": "Ved Singh",
                "session_id": 1,
                "question": "Is there any extra reading material for the science chapter on plants?",
                "status": "pending",
                "teacher_reply": "",
                "raised_at": "2026-04-13T08:00:00+05:30",
                "resolved_at": None,
            },
        ],

        # ── Teacher invite tokens created by the admin dashboard ──────────────
        # The admin sends an invite email with a link that contains the token.
        # On first open the teacher completes signup and picks their classes.
        "teacherInvites": {
            "demo-invite-2026": {
                "token": "demo-invite-2026",
                "email": "newteacher@greenfield.edu",
                "school_slug": "greenfield-public-school",
                "school_name": "Greenfield Public School",
                "valid": True,
            }
        },

        # ── Teacher's saved weekly schedule preferences ───────────────────────
        # Populated during first-week class selection.  Schema:
        # {"classroomIds": [1, 2], "setupCompleted": true, "setupCompletedAt": "2026-04-17"}
        "schedulePreferences": {},

        # ── SOS events from driver app ────────────────────────────────────────
        "sosEvents": [],
    }


STATE = _base_state()


# ── State lifecycle ───────────────────────────────────────────────────────────

def reset_demo_state() -> dict:
    """Reset the in-memory state back to the base fixture."""
    global STATE
    STATE = _base_state()
    return STATE


def get_state() -> dict:
    return STATE


# ── Auth helpers ──────────────────────────────────────────────────────────────

def login_payload(role: str) -> dict:
    """Return the login payload for the given role."""
    return deepcopy(STATE["users"][role])


# ── Parent / driver domain ────────────────────────────────────────────────────

def parent_dashboard() -> dict:
    return {
        "student": deepcopy(STATE["student"]),
        "trip": {
            "id": STATE["trip"]["id"],
            "routeName": STATE["trip"]["routeName"],
            "busLabel": STATE["trip"]["busLabel"],
            "etaMinutes": STATE["trip"]["etaMinutes"],
            "status": STATE["trip"]["status"],
            "busLocation": deepcopy(STATE["trip"]["busLocation"]),
        },
        "progress": deepcopy(STATE["progress"]),
        "dailyReports": deepcopy(STATE["dailyReports"]),
        "messages": deepcopy(STATE["messages"]),
        "alerts": deepcopy(STATE["alerts"]),
    }


def driver_dashboard() -> dict:
    return {
        "vehicle": deepcopy(STATE["vehicle"]),
        "trip": deepcopy(STATE["trip"]),
        "students": deepcopy(STATE["students"]),
        "renewals": deepcopy(STATE["renewals"]),
        "devices": deepcopy(STATE["devices"]),
    }


# ── Teacher / classroom domain ────────────────────────────────────────────────

def teacher_dashboard() -> dict:
    """Return the full teacher dashboard payload sorted by current session first."""
    roster = sorted(STATE["roster"], key=lambda item: item["isPresent"])
    return {
        "schedule": deepcopy(sorted(STATE["schedule"], key=lambda item: (not item["isCurrent"], item["startsAt"]))),
        "roster": deepcopy(roster),
        "dailyPreview": deepcopy(STATE["teacherDailyPreview"]),
    }


def list_classrooms() -> list:
    """Return all classrooms available for the class-picker feature."""
    return deepcopy(STATE["classrooms"])


def mark_attendance(session_id: int, student_id: int, is_present: bool = True) -> dict | None:
    """Mark a student present or absent for a given class session.

    When marking present on a school_entry boundary, a parent alert is injected.
    When marking present on a school_exit boundary, a school-concluded alert fires.
    is_present=False records an absence without triggering boundary alerts.
    """
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    student = next((item for item in STATE["roster"] if item["id"] == student_id), None)
    if not session or not student:
        return None

    student["isPresent"] = is_present
    student["isAbsent"] = not is_present

    alert_hint = None
    if is_present:
        if session["attendanceBoundary"] == "school_entry":
            alert_hint = "school_started"
            STATE["alerts"].insert(0, {
                "id": 300 + student_id,
                "title": "Student active in school",
                "body": f"{student['fullName']} was marked active in school during the first class.",
                "level": "info",
                "createdAt": "2026-04-13T08:05:00+05:30",
            })
        elif session["attendanceBoundary"] == "school_exit":
            alert_hint = "school_concluded"
            STATE["alerts"].insert(0, {
                "id": 400 + student_id,
                "title": "School day concluded",
                "body": f"{student['fullName']} was marked school concluded in the final class.",
                "level": "info",
                "createdAt": "2026-04-13T15:10:00+05:30",
            })

    return {
        "studentId": student_id,
        "isPresent": is_present,
        "event_type": session["attendanceBoundary"] if is_present else "absent",
        "alert_hint": alert_hint,
    }


def add_comment(session_id: int, student_id: int, note: str, category: str = "teacher_comment") -> dict | None:
    """Add a teacher progress note for a student, visible in the parent app."""
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    student = next((item for item in STATE["roster"] if item["id"] == student_id), None)
    if not session or not student:
        return None

    item = {
        "id": len(STATE["progress"]) + 1,
        "student_id": student_id,
        "classroom_id": 1,
        "session_id": session_id,
        "title": f"Teacher note for {student['fullName']}",
        "category": category,
        "note": note,
        "isReadByParent": False,
        "createdAt": "2026-04-13T12:00:00+05:30",
    }
    STATE["progress"].insert(0, item)
    student["latestComment"] = note

    # Keep daily report counts in sync
    STATE["dailyReports"][0]["teacherCommentSummary"] = (
        f"{len(STATE['progress'])} teacher notes are available for today."
    )
    STATE["dailyReports"][0]["unreadCommentCount"] = len(
        [e for e in STATE["progress"] if not e["isReadByParent"]]
    )

    # Update the per-student preview strip for the Reports tab
    for preview in STATE["teacherDailyPreview"]:
        if preview["studentName"] == student["fullName"]:
            preview["unreadCommentCount"] += 1
            preview["summary"] = (
                f"Present across the day. {preview['unreadCommentCount']} "
                "teacher comment(s) are still unread by the parent."
            )
            break

    return deepcopy(item)


# ── Broadcast helpers ─────────────────────────────────────────────────────────

def send_broadcast(session_id: int, message: str) -> dict | None:
    """Send a broadcast message to all parents of students in the session's class.

    In production this would fan out push notifications.  In demo mode we store
    the broadcast and also insert it into the parent messages feed so the parent
    app shows it immediately.
    """
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    if not session:
        return None

    broadcast = {
        "id": len(STATE["broadcasts"]) + 1,
        "session_id": session_id,
        "classroom_label": session["classroomLabel"],
        "message": message,
        "sent_at": "2026-04-13T12:00:00+05:30",
    }
    STATE["broadcasts"].insert(0, broadcast)

    # Mirror into the parent messages feed so the demo parent app sees it
    STATE["messages"].insert(0, {
        "id": 200 + broadcast["id"],
        "title": f"Message from class teacher ({session['classroomLabel']})",
        "body": message,
        "tag": "Class Update",
        "createdAt": "2026-04-13T12:00:00+05:30",
        "isRead": False,
    })

    return deepcopy(broadcast)


def list_broadcasts(session_id: int) -> list:
    """Return all broadcasts sent for a given session, newest first."""
    return deepcopy([b for b in STATE["broadcasts"] if b["session_id"] == session_id])


# ── Assist-request helpers ────────────────────────────────────────────────────

def list_assist_requests(session_id: int) -> list:
    """Return all pending assist requests raised by parents for a session."""
    return deepcopy([
        r for r in STATE["assistRequests"]
        if r["session_id"] == session_id and r["status"] == "pending"
    ])


def resolve_assist_request(request_id: int, reply: str = "") -> dict | None:
    """Mark an assist request as resolved, optionally storing the teacher's reply."""
    req = next((r for r in STATE["assistRequests"] if r["id"] == request_id), None)
    if not req:
        return None
    req["status"] = "resolved"
    req["teacher_reply"] = reply
    req["resolved_at"] = "2026-04-13T12:30:00+05:30"
    return deepcopy(req)


# ── Invite helpers ────────────────────────────────────────────────────────────

def validate_invite(token: str) -> dict | None:
    """Return invite metadata if the token is valid, or None if not found / used."""
    invite = STATE["teacherInvites"].get(token)
    if not invite or not invite["valid"]:
        return None
    return deepcopy(invite)


def accept_invite(token: str, name: str, phone: str) -> dict | None:
    """Complete teacher signup via an invite token.

    Marks the invite as used and returns a login payload flagged for first-week
    class-selection onboarding.
    """
    invite = STATE["teacherInvites"].get(token)
    if not invite or not invite["valid"]:
        return None

    # Mark invite as consumed
    invite["valid"] = False

    # Register teacher in the demo user store
    STATE["users"]["teacher"]["name"] = name

    return {
        "role": "teacher",
        "token": "demo-teacher-token",
        "name": name,
        "school_slug": invite["school_slug"],
        "is_first_week": True,
    }


# ── Schedule-preference helpers ───────────────────────────────────────────────

def save_schedule_preferences(classroom_ids: list[int]) -> dict:
    """Persist the teacher's first-week classroom selections.

    Marks setup as complete so the app no longer shows the first-week banner.
    classroom_ids contains the ids of classrooms the teacher selected.
    """
    prefs = {
        "classroomIds": classroom_ids,
        "setupCompleted": True,
        "setupCompletedAt": "2026-04-17",
    }
    STATE["schedulePreferences"] = prefs

    # Remove the first-week flag from the login payload so next login is normal
    STATE["users"]["teacher"]["is_first_week"] = False

    return deepcopy(prefs)


def parent_report(student_id: int) -> dict:
    """Return unread progress notes and daily reports for a parent."""
    unread = [item for item in STATE["progress"] if item["student_id"] == student_id and not item["isReadByParent"]]
    return {
        "unread_comment_count": len(unread),
        "unread_comments_preview": deepcopy(unread[:3]),
        "daily_reports": deepcopy(STATE["dailyReports"][:7]),
    }


# ── Tracking / transport helpers ──────────────────────────────────────────────

def tracking_trip(trip_id: int) -> dict | None:
    if STATE["trip"]["id"] != trip_id:
        return None
    return {
        "id": STATE["trip"]["id"],
        "school_id": 1,
        "route_id": 1,
        "route_name": STATE["trip"]["routeName"],
        "vehicle_id": STATE["vehicle"]["id"],
        "vehicle_registration_number": STATE["vehicle"]["registrationNumber"],
        "driver_id": 1,
        "driver_username": STATE["users"]["driver"]["name"],
        "status": STATE["trip"]["status"],
        "started_at": "2026-04-13T07:30:00+05:30" if STATE["trip"]["status"] != "scheduled" else None,
        "ended_at": "2026-04-13T08:45:00+05:30" if STATE["trip"]["status"] == "completed" else None,
        "latest_location": {
            "id": 1,
            "trip_id": STATE["trip"]["id"],
            "latitude": STATE["trip"]["busLocation"]["latitude"],
            "longitude": STATE["trip"]["busLocation"]["longitude"],
            "speed": STATE["trip"]["busLocation"]["speed"],
            "heading": STATE["trip"]["busLocation"]["heading"],
            "accuracy": 8.5,
            "provider": "google_maps",
            "created_at": STATE["trip"]["busLocation"]["updatedAt"],
        },
    }


def tracking_fleet() -> list[dict]:
    trip = tracking_trip(STATE["trip"]["id"])
    return [trip] if trip and STATE["trip"]["status"] in {"active", "arriving"} else []


def start_trip(trip_id: int) -> dict | None:
    if STATE["trip"]["id"] != trip_id:
        return None
    STATE["trip"]["status"] = "active"
    STATE["trip"]["tripState"] = "active"
    return deepcopy(STATE["trip"])


def end_trip(trip_id: int) -> dict | None:
    if STATE["trip"]["id"] != trip_id:
        return None
    STATE["trip"]["status"] = "completed"
    STATE["trip"]["tripState"] = "completed"
    return deepcopy(STATE["trip"])


def board_student(student_id: int) -> dict | None:
    for student in STATE["students"]:
        if student["id"] == student_id:
            student["status"] = "boarded"
            STATE["trip"]["boardedCount"] = sum(
                1 for item in STATE["students"] if item["status"] in {"boarded", "dropped"}
            )
            return deepcopy(student)
    return None


def drop_student(student_id: int) -> dict | None:
    for student in STATE["students"]:
        if student["id"] == student_id:
            student["status"] = "dropped"
            return deepcopy(student)
    return None


def trigger_sos() -> dict:
    event = {
        "id": len(STATE["sosEvents"]) + 1,
        "status": "open",
        "tripId": STATE["trip"]["id"],
    }
    STATE["sosEvents"].append(event)
    STATE["alerts"].insert(0, {
        "id": 100 + event["id"],
        "title": "Emergency alert triggered",
        "body": "SOS was triggered for the active route. School and parents were notified.",
        "level": "critical",
        "createdAt": "2026-04-13T12:40:00+05:30",
    })
    return deepcopy(event)
