from __future__ import annotations

from copy import deepcopy

# ---------------------------------------------------------------------------
# Demo in-memory state
#
# All backend views run in demo mode — no database queries are made.
# This module owns the single mutable STATE dict that simulates a real school's
# data.  Every view function reads/writes this dict via the helpers below.
#
# Sections of STATE:
#   users               – login payloads keyed by role
#   student/trip/vehicle/students/renewals/devices  – driver + parent domains
#   messages/alerts/progress/dailyReports           – parent feed domain
#   schedule/roster/teacherDailyPreview             – teacher attendance domain
#   classrooms          – full list of classrooms for the class-picker feature
#   broadcasts          – class-wide broadcast messages sent by teachers
#   assistRequests      – parent-raised doubt/help cards per student
#   teacherInvites      – invite tokens generated by admin dashboard
#   schedulePreferences – teacher's saved weekly schedule (first-week setup)
#   sosEvents           – SOS events from driver app
#   breakdownEvents     – Breakdown events from driver app
#   availableRoutes     – routes parents can assign their ward to
#   driverContact       – current trip driver's contact info
#   studentStopOverrides – parent-customised pick-up/drop-off stops per student
#   firstTripConfirmations – pending stop auto-assignment confirmations
#   locationPings       – latest 1-min GPS ping per trip (req 1)
#   tripHistory         – completed trip records saved to "DB" (req 2)
#   nearbyVehicles      – other school buses visible in breakdown mode (req 12)
#   driverInvites       – admin-generated driver invite tokens
#   driverSignupRequests – self-signup requests pending admin approval
#   driverVehicles      – all vehicles assigned to the demo driver (multi-vehicle, req 13)
# ---------------------------------------------------------------------------


def _base_state() -> dict:
    return {
        # ── Auth payloads ────────────────────────────────────────────────────
        "users": {
            "parent": {
                "role": "parent",
                "token": "demo-parent-token",
                "name": "Aarav's Parent",
                "school_slug": "greenfield-public-school",
            },
            "driver": {
                "role": "driver",
                "token": "demo-driver-token",
                "name": "Rohit Kumar",
                "school_slug": "greenfield-public-school",
                # is_pending_approval is set to True for self-signup until admin approves
                "is_pending_approval": False,
                # aadhar_number ties multiple vehicles to the same driver identity
                "aadhar_number": "XXXX-XXXX-1234",
            },
            "teacher": {
                "role": "teacher",
                "token": "demo-teacher-token",
                "name": "Ms. Sen",
                "school_slug": "greenfield-public-school",
                # is_first_week drives the first-week class-selection onboarding
                # flow in the teacher app.  Set to False once the teacher has
                # saved their schedule_preferences.
                "is_first_week": True,
            },
        },

        # ── Parent / student domain ──────────────────────────────────────────
        "student": {
            "id": 1,
            "name": "Aarav Roy",
            "grade": "Class 4B",
            "routeName": "North Route A",
            "stopName": "Lakeview Stop",
            "routeId": 1,
        },
        "trip": {
            "id": 201,
            "routeName": "North Route A",
            "busLabel": "Bus 12",
            "vehicleLabel": "Bus 12",
            "shift": "morning",
            "status": "scheduled",
            "tripState": "scheduled",
            "etaMinutes": 8,
            "boardedCount": 1,
            "totalCount": 4,
            "nextStop": "Lakeview Stop",
            "busLocation": {
                "latitude": 22.5726,
                "longitude": 88.3639,
                "speed": 24,
                "heading": 140,
                "updatedAt": "2026-04-17T10:15:00+05:30",
            },
        },
        "vehicle": {
            "id": 1,
            "registrationNumber": "WB-04-AB-1288",
            "label": "Bus 12",
            "routeName": "North Route A",
            "capacity": 42,
        },
        "students": [
            {"id": 1, "name": "Aarav Roy",  "stopName": "Lakeview Stop", "status": "boarded"},
            {"id": 2, "name": "Mira Dutta", "stopName": "Pine Street",   "status": "boarded"},
            {"id": 3, "name": "Ved Singh",  "stopName": "Metro Corner",  "status": "dropped"},
            {"id": 4, "name": "Sia Das",    "stopName": "City Center",   "status": "absent"},
        ],
        "renewals": [
            {"id": 1, "title": "Vehicle fitness certificate", "expiresOn": "2026-04-20", "priority": "urgent"},
            {"id": 2, "title": "Pollution certificate",       "expiresOn": "2026-05-07", "priority": "normal"},
            {"id": 3, "title": "Insurance renewal",           "expiresOn": "2026-05-15", "priority": "normal"},
        ],
        "devices": [
            {"id": 1, "label": "Samsung A54",          "platform": "Android", "isCurrent": True},
            {"id": 2, "label": "School Backup Phone",  "platform": "Android", "isCurrent": False},
        ],
        "messages": [
            {
                "id": 1,
                "title": "Summer activity registrations open",
                "body": "Parents can now enroll students in the school summer activity camp from the message center.",
                "tag": "Update",
                "createdAt": "2026-04-12T09:30:00+05:30",
                "isRead": False,
            },
            {
                "id": 2,
                "title": "Partner offer: school supplies",
                "body": "Discounted notebooks and art kits are available this week through the school partner store.",
                "tag": "Offer",
                "createdAt": "2026-04-10T12:00:00+05:30",
                "isRead": True,
            },
        ],
        "alerts": [
            {
                "id": 1,
                "title": "Bus is 2 stops away",
                "body": "Bus 12 is approaching Lakeview Stop.",
                "level": "info",
                "createdAt": "2026-04-17T10:10:00+05:30",
            },
            {
                "id": 2,
                "title": "Student boarded safely",
                "body": "Aarav boarded Bus 12 at 7:42 AM.",
                "level": "info",
                "createdAt": "2026-04-17T07:42:00+05:30",
            },
        ],
        "progress": [
            {
                "id": 1,
                "student_id": 1,
                "title": "Strong reading progress",
                "note": "Completed the weekly reading task confidently and helped peers during discussion.",
                "category": "Academic",
                "createdAt": "2026-04-12T14:00:00+05:30",
                "isReadByParent": False,
            },
            {
                "id": 2,
                "student_id": 1,
                "title": "Great class participation",
                "note": "Volunteered answers in science and stayed engaged through the full session.",
                "category": "Participation",
                "createdAt": "2026-04-11T11:30:00+05:30",
                "isReadByParent": True,
            },
        ],
        "dailyReports": [
            {
                "id": 1,
                "date": "2026-04-17",
                "attendanceSummary": "Present across all scheduled classes.",
                "teacherCommentSummary": "2 teacher notes were added today.",
                "unreadCommentCount": 1,
            }
        ],

        # ── Teacher / classroom domain ───────────────────────────────────────
        "schedule": [
            {
                "id": 1,
                "classroomLabel": "Class 4B",
                "title": "Morning Attendance",
                "startsAt": "08:00",
                "endsAt": "08:30",
                "isCurrent": True,
                "attendanceBoundary": "school_entry",
            },
            {
                "id": 2,
                "classroomLabel": "Class 4B",
                "title": "Science",
                "startsAt": "10:00",
                "endsAt": "10:45",
                "isCurrent": False,
                "attendanceBoundary": "none",
            },
            {
                "id": 3,
                "classroomLabel": "Class 4B",
                "title": "Closing Period",
                "startsAt": "14:45",
                "endsAt": "15:10",
                "isCurrent": False,
                "attendanceBoundary": "school_exit",
            },
        ],
        "roster": [
            {"id": 1, "fullName": "Aarav Roy",    "rollNumber": "04", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 2, "fullName": "Mira Dutta",   "rollNumber": "07", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 3, "fullName": "Ved Singh",    "rollNumber": "11", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 4, "fullName": "Sia Das",      "rollNumber": "18", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 5, "fullName": "Rohan Mehta",  "rollNumber": "22", "isPresent": False, "isAbsent": False, "latestComment": ""},
            {"id": 6, "fullName": "Priya Sharma", "rollNumber": "25", "isPresent": False, "isAbsent": False, "latestComment": ""},
        ],
        "teacherDailyPreview": [
            {
                "studentName": "Aarav Roy",
                "unreadCommentCount": 1,
                "summary": "Present across the day. Two teacher comments; one still unread by parent.",
            },
            {
                "studentName": "Mira Dutta",
                "unreadCommentCount": 0,
                "summary": "Present across the day. No unread teacher comments remaining.",
            },
        ],

        # ── Classrooms list – used by the class-picker feature ───────────────
        "classrooms": [
            {"id": 1, "name": "Class 4", "section": "B", "label": "Class 4B"},
            {"id": 2, "name": "Class 5", "section": "A", "label": "Class 5A"},
            {"id": 3, "name": "Class 3", "section": "C", "label": "Class 3C"},
            {"id": 4, "name": "Class 6", "section": "A", "label": "Class 6A"},
            {"id": 5, "name": "Class 7", "section": "B", "label": "Class 7B"},
            {"id": 6, "name": "Class 2", "section": "A", "label": "Class 2A"},
        ],

        # ── Class-wide broadcasts sent by the teacher ────────────────────────
        "broadcasts": [],

        # ── Assist requests raised by parents ────────────────────────────────
        "assistRequests": [
            {
                "id": 1,
                "student_id": 1,
                "student_name": "Aarav Roy",
                "session_id": 1,
                "question": "Could you clarify the fractions homework from yesterday? Aarav got confused and we weren't able to help at home.",
                "status": "pending",
                "teacher_reply": "",
                "raised_at": "2026-04-17T07:45:00+05:30",
                "resolved_at": None,
            },
            {
                "id": 2,
                "student_id": 3,
                "student_name": "Ved Singh",
                "session_id": 1,
                "question": "Is there any extra reading material for the science chapter on plants?",
                "status": "pending",
                "teacher_reply": "",
                "raised_at": "2026-04-17T08:00:00+05:30",
                "resolved_at": None,
            },
        ],

        # ── Teacher invite tokens created by the admin dashboard ──────────────
        "teacherInvites": {
            "demo-invite-2026": {
                "token": "demo-invite-2026",
                "email": "newteacher@greenfield.edu",
                "school_slug": "greenfield-public-school",
                "school_name": "Greenfield Public School",
                "valid": True,
            }
        },

        # ── Teacher's saved weekly schedule preferences ───────────────────────
        "schedulePreferences": {},

        # ── SOS events from driver app ────────────────────────────────────────
        "sosEvents": [],

        # ── Breakdown events from driver app (req 10/11) ──────────────────────
        # When a driver triggers a breakdown, an alert is sent to all parents
        # and the driver can contact nearby vehicles for assistance.
        "breakdownEvents": [],

        # ── Routes available for parent bus assignment (req 3) ────────────────
        # Parents can pick their ward's route during signup or change it later.
        "availableRoutes": [
            {
                "id": 1,
                "name": "North Route A",
                "busLabel": "Bus 12",
                "vehicleId": 1,
                "driverName": "Rohit Kumar",
                "stops": ["Lakeview Stop", "Pine Street", "Metro Corner", "City Center"],
            },
            {
                "id": 2,
                "name": "South Route B",
                "busLabel": "Bus 7",
                "vehicleId": 2,
                "driverName": "Anil Sharma",
                "stops": ["Riverside Gate", "Flower Market", "Station Road", "Town Square"],
            },
            {
                "id": 3,
                "name": "East Route C",
                "busLabel": "Bus 3",
                "vehicleId": 3,
                "driverName": "Suresh Patil",
                "stops": ["Sunrise Colony", "Park View", "School Lane"],
            },
        ],

        # ── Driver contact info for parent (req 4) ────────────────────────────
        # Parents can fetch this at any time to reach the active trip's driver.
        "driverContact": {
            "name": "Rohit Kumar",
            "phone": "+91 98765 43210",
            "vehicleLabel": "Bus 12",
            "routeName": "North Route A",
        },

        # ── Parent-customised pick-up / drop-off stops per student (req 7) ───
        # Keys are student_id (str).  Each entry overrides the default route stop.
        # {str(student_id): {"stopName": ..., "latitude": ..., "longitude": ..., "setAt": ...}}
        "studentStopOverrides": {},

        # ── First-trip stop auto-assignment confirmations (req 8) ─────────────
        # When a student is boarded for the very first time the location is
        # suggested as their scheduled stop. Both parent and driver must confirm.
        # {str(student_id): {"status": "pending"|"parent_confirmed"|"confirmed",
        #                     "stopName": ..., "latitude": ..., "longitude": ...}}
        "firstTripConfirmations": {},

        # ── 1-min location pings from driver during active trip (req 1) ───────
        # {str(trip_id): {latitude, longitude, speed, heading, updatedAt}}
        # The parent LiveTrackScreen polls this every 60 s.
        "locationPings": {},

        # ── Saved trip history (req 2) ────────────────────────────────────────
        # Every completed trip is appended here as a permanent record.
        "tripHistory": [],

        # ── Nearby school vehicles for breakdown assistance (req 12) ──────────
        # Driver can contact nearby vehicles when a breakdown is declared.
        "nearbyVehicles": [
            {
                "id": 2,
                "label": "Bus 7",
                "driverName": "Anil Sharma",
                "phone": "+91 98111 22333",
                "routeName": "South Route B",
                "distanceKm": 1.4,
            },
            {
                "id": 3,
                "label": "Bus 3",
                "driverName": "Suresh Patil",
                "phone": "+91 97444 55666",
                "routeName": "East Route C",
                "distanceKm": 2.8,
            },
        ],

        # ── Driver invite tokens (req 6) ──────────────────────────────────────
        # Admin dashboard generates these and emails them to prospective drivers.
        "driverInvites": {
            "demo-driver-invite-2026": {
                "token": "demo-driver-invite-2026",
                "school_slug": "greenfield-public-school",
                "school_name": "Greenfield Public School",
                "valid": True,
            }
        },

        # ── Driver self-signup requests (req 6) ───────────────────────────────
        # When a driver signs up without an invite they choose a school and wait
        # for admin approval.  The driver app shows a "Pending Approval" screen
        # until the admin approves the request from the dashboard.
        "driverSignupRequests": [],

        # ── Dismissal / pickup-intent queue ───────────────────────────────────
        # Parents signal their ETA for car-pickup dismissal.  School staff see a
        # live queue sorted by ETA and tap "Child is ready" to notify the parent.
        # status: pending | notified | completed
        "pickupIntents": [
            {
                "id": 1,
                "student_id": 1,
                "student_name": "Aarav Roy",
                "parent_name": "Aarav's Parent",
                "classroom": "Class 4B",
                "eta_minutes": 0,
                "status": "pending",
                "created_at": "2026-04-22T14:45:00+05:30",
                "notified_at": None,
                "completed_at": None,
            },
            {
                "id": 2,
                "student_id": 5,
                "student_name": "Rohan Mehta",
                "parent_name": "Rohan's Parent",
                "classroom": "Class 4B",
                "eta_minutes": 1,
                "status": "pending",
                "created_at": "2026-04-22T14:44:00+05:30",
                "notified_at": None,
                "completed_at": None,
            },
            {
                "id": 3,
                "student_id": 6,
                "student_name": "Priya Sharma",
                "parent_name": "Priya's Parent",
                "classroom": "Class 5A",
                "eta_minutes": 5,
                "status": "pending",
                "created_at": "2026-04-22T14:43:00+05:30",
                "notified_at": None,
                "completed_at": None,
            },
            {
                "id": 4,
                "student_id": 3,
                "student_name": "Ved Singh",
                "parent_name": "Ved's Parent",
                "classroom": "Class 4B",
                "eta_minutes": 5,
                "status": "notified",
                "created_at": "2026-04-22T14:40:00+05:30",
                "notified_at": "2026-04-22T14:46:00+05:30",
                "completed_at": None,
            },
            {
                "id": 5,
                "student_id": 2,
                "student_name": "Mira Dutta",
                "parent_name": "Mira's Parent",
                "classroom": "Class 5A",
                "eta_minutes": 10,
                "status": "pending",
                "created_at": "2026-04-22T14:42:00+05:30",
                "notified_at": None,
                "completed_at": None,
            },
            {
                "id": 6,
                "student_id": 4,
                "student_name": "Sia Das",
                "parent_name": "Sia's Parent",
                "classroom": "Class 6A",
                "eta_minutes": 10,
                "status": "completed",
                "created_at": "2026-04-22T14:30:00+05:30",
                "notified_at": "2026-04-22T14:35:00+05:30",
                "completed_at": "2026-04-22T14:38:00+05:30",
            },
        ],
        "_dismissal_id_counter": 7,

        # ── Multi-vehicle assignment for the demo driver (req 13) ─────────────
        # A driver is identified by aadhar_number; multiple vehicles can be
        # assigned to the same aadhar. Each vehicle has its own phone number
        # recorded on the assignment for parent contact purposes.
        "driverVehicles": [
            {
                "id": 1,
                "registrationNumber": "WB-04-AB-1288",
                "label": "Bus 12",
                "routeName": "North Route A",
                "capacity": 42,
                "isActive": True,
                "contactPhone": "+91 98765 43210",
            },
            {
                "id": 2,
                "registrationNumber": "WB-04-AB-9901",
                "label": "Bus 7",
                "routeName": "South Route B",
                "capacity": 38,
                "isActive": False,
                "contactPhone": "+91 91234 56789",
            },
        ],
    }


STATE = _base_state()


# ── State lifecycle ───────────────────────────────────────────────────────────

def reset_demo_state() -> dict:
    """Reset the in-memory state back to the base fixture."""
    global STATE
    STATE = _base_state()
    return STATE


def get_state() -> dict:
    return STATE


# ── Auth helpers ──────────────────────────────────────────────────────────────

def login_payload(role: str) -> dict:
    """Return the login payload for the given role."""
    return deepcopy(STATE["users"][role])


# ── Parent / driver domain ────────────────────────────────────────────────────

def parent_dashboard() -> dict:
    student = deepcopy(STATE["student"])
    # Attach the current stop override if one exists
    override = STATE["studentStopOverrides"].get(str(student["id"]))
    if override:
        student["stopName"] = override["stopName"]
    return {
        "student": student,
        "trip": {
            "id": STATE["trip"]["id"],
            "routeName": STATE["trip"]["routeName"],
            "busLabel": STATE["trip"]["busLabel"],
            "etaMinutes": STATE["trip"]["etaMinutes"],
            "status": STATE["trip"]["status"],
            "busLocation": deepcopy(STATE["trip"]["busLocation"]),
        },
        "progress": deepcopy(STATE["progress"]),
        "dailyReports": deepcopy(STATE["dailyReports"]),
        "messages": deepcopy(STATE["messages"]),
        "alerts": deepcopy(STATE["alerts"]),
        "driverContact": deepcopy(STATE["driverContact"]),
    }


def driver_dashboard() -> dict:
    # Return the currently active vehicle alongside all assigned vehicles so
    # the driver can switch between them on the DashboardScreen.
    return {
        "vehicle": deepcopy(STATE["vehicle"]),
        "trip": deepcopy(STATE["trip"]),
        "students": deepcopy(STATE["students"]),
        "renewals": deepcopy(STATE["renewals"]),
        "devices": deepcopy(STATE["devices"]),
        "driverVehicles": deepcopy(STATE["driverVehicles"]),
    }


# ── Teacher / classroom domain ────────────────────────────────────────────────

def teacher_dashboard() -> dict:
    """Return the full teacher dashboard payload sorted by current session first."""
    roster = sorted(STATE["roster"], key=lambda item: item["isPresent"])
    return {
        "schedule": deepcopy(sorted(STATE["schedule"], key=lambda item: (not item["isCurrent"], item["startsAt"]))),
        "roster": deepcopy(roster),
        "dailyPreview": deepcopy(STATE["teacherDailyPreview"]),
    }


def list_classrooms() -> list:
    """Return all classrooms available for the class-picker feature."""
    return deepcopy(STATE["classrooms"])


def mark_attendance(session_id: int, student_id: int, is_present: bool = True) -> dict | None:
    """Mark a student present or absent for a given class session.

    When marking present on a school_entry boundary, a parent alert is injected.
    When marking present on a school_exit boundary, a school-concluded alert fires.
    is_present=False records an absence without triggering boundary alerts.
    """
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    student = next((item for item in STATE["roster"] if item["id"] == student_id), None)
    if not session or not student:
        return None

    student["isPresent"] = is_present
    student["isAbsent"] = not is_present

    alert_hint = None
    if is_present:
        if session["attendanceBoundary"] == "school_entry":
            alert_hint = "school_started"
            STATE["alerts"].insert(0, {
                "id": 300 + student_id,
                "title": "Student active in school",
                "body": f"{student['fullName']} was marked active in school during the first class.",
                "level": "info",
                "createdAt": "2026-04-17T08:05:00+05:30",
            })
        elif session["attendanceBoundary"] == "school_exit":
            alert_hint = "school_concluded"
            STATE["alerts"].insert(0, {
                "id": 400 + student_id,
                "title": "School day concluded",
                "body": f"{student['fullName']} was marked school concluded in the final class.",
                "level": "info",
                "createdAt": "2026-04-17T15:10:00+05:30",
            })

    return {
        "studentId": student_id,
        "isPresent": is_present,
        "event_type": session["attendanceBoundary"] if is_present else "absent",
        "alert_hint": alert_hint,
    }


def add_comment(session_id: int, student_id: int, note: str, category: str = "teacher_comment") -> dict | None:
    """Add a teacher progress note for a student, visible in the parent app."""
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    student = next((item for item in STATE["roster"] if item["id"] == student_id), None)
    if not session or not student:
        return None

    item = {
        "id": len(STATE["progress"]) + 1,
        "student_id": student_id,
        "classroom_id": 1,
        "session_id": session_id,
        "title": f"Teacher note for {student['fullName']}",
        "category": category,
        "note": note,
        "isReadByParent": False,
        "createdAt": "2026-04-17T12:00:00+05:30",
    }
    STATE["progress"].insert(0, item)
    student["latestComment"] = note

    STATE["dailyReports"][0]["teacherCommentSummary"] = (
        f"{len(STATE['progress'])} teacher notes are available for today."
    )
    STATE["dailyReports"][0]["unreadCommentCount"] = len(
        [e for e in STATE["progress"] if not e["isReadByParent"]]
    )

    for preview in STATE["teacherDailyPreview"]:
        if preview["studentName"] == student["fullName"]:
            preview["unreadCommentCount"] += 1
            preview["summary"] = (
                f"Present across the day. {preview['unreadCommentCount']} "
                "teacher comment(s) are still unread by the parent."
            )
            break

    return deepcopy(item)


# ── Broadcast helpers ─────────────────────────────────────────────────────────

def send_broadcast(session_id: int, message: str) -> dict | None:
    """Send a broadcast message to all parents of students in the session's class."""
    session = next((item for item in STATE["schedule"] if item["id"] == session_id), None)
    if not session:
        return None

    broadcast = {
        "id": len(STATE["broadcasts"]) + 1,
        "session_id": session_id,
        "classroom_label": session["classroomLabel"],
        "message": message,
        "sent_at": "2026-04-17T12:00:00+05:30",
    }
    STATE["broadcasts"].insert(0, broadcast)

    STATE["messages"].insert(0, {
        "id": 200 + broadcast["id"],
        "title": f"Message from class teacher ({session['classroomLabel']})",
        "body": message,
        "tag": "Class Update",
        "createdAt": "2026-04-17T12:00:00+05:30",
        "isRead": False,
    })

    return deepcopy(broadcast)


def list_broadcasts(session_id: int) -> list:
    """Return all broadcasts sent for a given session, newest first."""
    return deepcopy([b for b in STATE["broadcasts"] if b["session_id"] == session_id])


# ── Assist-request helpers ────────────────────────────────────────────────────

def list_assist_requests(session_id: int) -> list:
    """Return all pending assist requests raised by parents for a session."""
    return deepcopy([
        r for r in STATE["assistRequests"]
        if r["session_id"] == session_id and r["status"] == "pending"
    ])


def resolve_assist_request(request_id: int, reply: str = "") -> dict | None:
    """Mark an assist request as resolved, optionally storing the teacher's reply."""
    req = next((r for r in STATE["assistRequests"] if r["id"] == request_id), None)
    if not req:
        return None
    req["status"] = "resolved"
    req["teacher_reply"] = reply
    req["resolved_at"] = "2026-04-17T12:30:00+05:30"
    return deepcopy(req)


# ── Teacher invite helpers ────────────────────────────────────────────────────

def validate_invite(token: str) -> dict | None:
    """Return invite metadata if the token is valid, or None if not found / used."""
    invite = STATE["teacherInvites"].get(token)
    if not invite or not invite["valid"]:
        return None
    return deepcopy(invite)


def accept_invite(token: str, name: str, phone: str) -> dict | None:
    """Complete teacher signup via an invite token."""
    invite = STATE["teacherInvites"].get(token)
    if not invite or not invite["valid"]:
        return None
    invite["valid"] = False
    STATE["users"]["teacher"]["name"] = name
    return {
        "role": "teacher",
        "token": "demo-teacher-token",
        "name": name,
        "school_slug": invite["school_slug"],
        "is_first_week": True,
    }


# ── Schedule-preference helpers ───────────────────────────────────────────────

def save_schedule_preferences(classroom_ids: list[int]) -> dict:
    """Persist the teacher's first-week classroom selections."""
    prefs = {
        "classroomIds": classroom_ids,
        "setupCompleted": True,
        "setupCompletedAt": "2026-04-17",
    }
    STATE["schedulePreferences"] = prefs
    STATE["users"]["teacher"]["is_first_week"] = False
    return deepcopy(prefs)


def parent_report(student_id: int) -> dict:
    """Return unread progress notes and daily reports for a parent."""
    unread = [item for item in STATE["progress"] if item["student_id"] == student_id and not item["isReadByParent"]]
    return {
        "unread_comment_count": len(unread),
        "unread_comments_preview": deepcopy(unread[:3]),
        "daily_reports": deepcopy(STATE["dailyReports"][:7]),
    }


# ── Transport / route helpers (req 1, 3, 4, 7, 8, 13) ───────────────────────

def list_available_routes() -> list:
    """Return all routes that a parent can assign their ward to (req 3)."""
    return deepcopy(STATE["availableRoutes"])


def change_student_bus(route_id: int) -> dict | None:
    """Assign the demo student to a different route (req 3).

    Updates the student's route and bus label in the demo state so the parent
    app home screen and live-track screen immediately reflect the change.
    """
    route = next((r for r in STATE["availableRoutes"] if r["id"] == route_id), None)
    if not route:
        return None
    STATE["student"]["routeName"] = route["name"]
    STATE["student"]["routeId"] = route["id"]
    STATE["trip"]["routeName"] = route["name"]
    STATE["trip"]["busLabel"] = route["busLabel"]
    STATE["trip"]["vehicleLabel"] = route["busLabel"]
    STATE["driverContact"]["name"] = route["driverName"]
    STATE["driverContact"]["vehicleLabel"] = route["busLabel"]
    STATE["driverContact"]["routeName"] = route["name"]
    return {"routeId": route_id, "routeName": route["name"], "busLabel": route["busLabel"]}


def get_driver_contact() -> dict:
    """Return the current trip driver's contact info (req 4)."""
    return deepcopy(STATE["driverContact"])


def update_student_stop(student_id: int, stop_name: str, latitude: float, longitude: float) -> dict:
    """Set or update a parent-customised pick-up/drop-off stop (req 7).

    The updated stop is shown to the driver on their RosterScreen for that
    student so the driver knows the new pickup/drop location.
    """
    override = {
        "stopName": stop_name,
        "latitude": latitude,
        "longitude": longitude,
        "setAt": "2026-04-17T09:00:00+05:30",
        "confirmedByParent": True,
        "confirmedByDriver": False,
    }
    STATE["studentStopOverrides"][str(student_id)] = override

    # Mirror the override into the student's ride-list entry for the driver app
    for s in STATE["students"]:
        if s["id"] == student_id:
            s["stopName"] = stop_name
            s["hasStopOverride"] = True
            break

    # Also update the parent-facing student record
    if STATE["student"]["id"] == student_id:
        STATE["student"]["stopName"] = stop_name

    return deepcopy(override)


def get_student_stop_override(student_id: int) -> dict | None:
    """Return a parent-set stop override for a student, or None."""
    return deepcopy(STATE["studentStopOverrides"].get(str(student_id)))


# ── First-trip stop auto-assignment (req 8) ───────────────────────────────────

def _check_first_trip(student_id: int, latitude: float, longitude: float, stop_name: str) -> dict | None:
    """If this is the student's first-ever board event, create a pending confirmation.

    Both parent and driver must confirm before the stop is permanently saved.
    Returns the pending confirmation record, or None if already confirmed/exists.
    """
    key = str(student_id)
    if key in STATE["studentStopOverrides"] or key in STATE["firstTripConfirmations"]:
        return None

    confirmation = {
        "status": "pending",
        "stopName": stop_name,
        "latitude": latitude,
        "longitude": longitude,
    }
    STATE["firstTripConfirmations"][key] = confirmation

    # Inject a parent notification asking them to confirm the pickup location
    student = next((s for s in STATE["students"] if s["id"] == student_id), None)
    student_name = student["name"] if student else f"Student #{student_id}"
    STATE["alerts"].insert(0, {
        "id": 500 + student_id,
        "title": "Confirm pickup location",
        "body": (
            f"{student_name} was picked up for the first time at {stop_name}. "
            "Please confirm this as your scheduled pickup point."
        ),
        "level": "warning",
        "createdAt": "2026-04-17T07:30:00+05:30",
        "actionType": "confirm_stop",
        "studentId": student_id,
    })
    return deepcopy(confirmation)


def confirm_first_trip_stop(student_id: int) -> dict | None:
    """Parent confirms the auto-suggested first-trip stop (req 8).

    Once both parent and driver confirm, the stop is saved as a permanent
    stop override for the student.
    """
    key = str(student_id)
    conf = STATE["firstTripConfirmations"].get(key)
    if not conf:
        return None

    conf["status"] = "parent_confirmed"

    # In demo mode treat parent confirmation as sufficient to auto-save
    update_student_stop(student_id, conf["stopName"], conf["latitude"], conf["longitude"])
    return deepcopy(conf)


# ── Location ping (req 1) ─────────────────────────────────────────────────────

def ping_location(trip_id: int, latitude: float, longitude: float, speed: float = 0, heading: float = 0) -> dict | None:
    """Store the latest 1-min GPS ping from the driver app (req 1).

    During an active trip the driver app calls this every 60 seconds.
    The parent LiveTrackScreen polls the tracking endpoint (also every 60 s)
    to pick up the freshest coordinate.
    """
    if STATE["trip"]["id"] != trip_id or STATE["trip"]["status"] not in {"active", "arriving"}:
        return None

    ping = {
        "trip_id": trip_id,
        "latitude": latitude,
        "longitude": longitude,
        "speed": speed,
        "heading": heading,
        "updatedAt": "2026-04-17T10:15:00+05:30",
    }
    STATE["locationPings"][str(trip_id)] = ping
    # Keep the main bus location in sync so /tracking/trips/{id}/live/ returns fresh data
    STATE["trip"]["busLocation"]["latitude"] = latitude
    STATE["trip"]["busLocation"]["longitude"] = longitude
    STATE["trip"]["busLocation"]["speed"] = speed
    STATE["trip"]["busLocation"]["heading"] = heading
    STATE["trip"]["busLocation"]["updatedAt"] = ping["updatedAt"]
    return deepcopy(ping)


# ── Tracking / transport helpers ──────────────────────────────────────────────

def tracking_trip(trip_id: int) -> dict | None:
    if STATE["trip"]["id"] != trip_id:
        return None
    return {
        "id": STATE["trip"]["id"],
        "school_id": 1,
        "route_id": 1,
        "route_name": STATE["trip"]["routeName"],
        "vehicle_id": STATE["vehicle"]["id"],
        "vehicle_registration_number": STATE["vehicle"]["registrationNumber"],
        "driver_id": 1,
        "driver_username": STATE["users"]["driver"]["name"],
        "driver_contact": deepcopy(STATE["driverContact"]),
        "status": STATE["trip"]["status"],
        "started_at": "2026-04-17T07:30:00+05:30" if STATE["trip"]["status"] != "scheduled" else None,
        "ended_at": "2026-04-17T08:45:00+05:30" if STATE["trip"]["status"] == "completed" else None,
        "latest_location": {
            "id": 1,
            "trip_id": STATE["trip"]["id"],
            "latitude": STATE["trip"]["busLocation"]["latitude"],
            "longitude": STATE["trip"]["busLocation"]["longitude"],
            "speed": STATE["trip"]["busLocation"]["speed"],
            "heading": STATE["trip"]["busLocation"]["heading"],
            "accuracy": 8.5,
            "provider": "google_maps",
            "created_at": STATE["trip"]["busLocation"]["updatedAt"],
        },
    }


def tracking_fleet() -> list[dict]:
    trip = tracking_trip(STATE["trip"]["id"])
    return [trip] if trip and STATE["trip"]["status"] in {"active", "arriving"} else []


def start_trip(trip_id: int) -> dict | None:
    if STATE["trip"]["id"] != trip_id:
        return None
    STATE["trip"]["status"] = "active"
    STATE["trip"]["tripState"] = "active"
    return deepcopy(STATE["trip"])


def end_trip(trip_id: int) -> dict | None:
    """End the active trip and save it to trip history (req 2).

    Any students still in 'boarded' status are treated as missed drops —
    a critical alert is injected into the parent alerts feed (req 9).
    """
    if STATE["trip"]["id"] != trip_id:
        return None

    # Detect missed drops (students still boarded when trip ends)
    missed = [s for s in STATE["students"] if s["status"] == "boarded"]
    for s in missed:
        STATE["alerts"].insert(0, {
            "id": 600 + s["id"],
            "title": "Missed drop alert",
            "body": (
                f"{s['name']} was not dropped off before the trip ended. "
                "Please contact the driver or school immediately."
            ),
            "level": "critical",
            "createdAt": "2026-04-17T08:50:00+05:30",
        })

    STATE["trip"]["status"] = "completed"
    STATE["trip"]["tripState"] = "completed"

    # Save a permanent trip record (req 2)
    record = {
        "id": len(STATE["tripHistory"]) + 1,
        "tripId": trip_id,
        "routeName": STATE["trip"]["routeName"],
        "busLabel": STATE["trip"]["busLabel"],
        "shift": STATE["trip"]["shift"],
        "startedAt": "2026-04-17T07:30:00+05:30",
        "endedAt": "2026-04-17T08:50:00+05:30",
        "boardedCount": STATE["trip"]["boardedCount"],
        "totalCount": STATE["trip"]["totalCount"],
        "missedDrops": [s["name"] for s in missed],
    }
    STATE["tripHistory"].append(record)

    return deepcopy(STATE["trip"])


def board_student(student_id: int) -> dict | None:
    """Board a student and trigger first-trip auto-assignment if needed (req 8)."""
    for student in STATE["students"]:
        if student["id"] == student_id:
            student["status"] = "boarded"
            STATE["trip"]["boardedCount"] = sum(
                1 for item in STATE["students"] if item["status"] in {"boarded", "dropped"}
            )
            # Check if this is the student's first ever trip — use the current
            # bus location as the auto-suggested pickup stop (req 8)
            loc = STATE["trip"]["busLocation"]
            stop_name = student.get("stopName", "Current Location")
            _check_first_trip(student_id, loc["latitude"], loc["longitude"], stop_name)
            return deepcopy(student)
    return None


def drop_student(student_id: int) -> dict | None:
    for student in STATE["students"]:
        if student["id"] == student_id:
            student["status"] = "dropped"
            return deepcopy(student)
    return None


# ── SOS / Breakdown helpers (req 10, 11) ─────────────────────────────────────

def trigger_sos() -> dict:
    """Trigger an SOS event and broadcast a critical alert to all parents (req 11)."""
    event = {
        "id": len(STATE["sosEvents"]) + 1,
        "status": "open",
        "tripId": STATE["trip"]["id"],
        "type": "sos",
    }
    STATE["sosEvents"].append(event)
    STATE["alerts"].insert(0, {
        "id": 100 + event["id"],
        "title": "EMERGENCY: SOS triggered",
        "body": "SOS was triggered on the active route. School and all route parents have been notified. Stay calm and follow safety protocols.",
        "level": "critical",
        "createdAt": "2026-04-17T12:40:00+05:30",
    })
    return deepcopy(event)


def trigger_breakdown() -> dict:
    """Trigger a breakdown event and alert all route parents (req 10, 11).

    Unlike SOS, a breakdown is not an emergency but still requires parents to
    be notified so they can arrange alternative transport.
    """
    event = {
        "id": len(STATE["breakdownEvents"]) + 1,
        "status": "open",
        "tripId": STATE["trip"]["id"],
        "type": "breakdown",
        "busLabel": STATE["trip"]["busLabel"],
        "routeName": STATE["trip"]["routeName"],
    }
    STATE["breakdownEvents"].append(event)
    STATE["alerts"].insert(0, {
        "id": 700 + event["id"],
        "title": "Vehicle breakdown on your route",
        "body": (
            f"{STATE['trip']['busLabel']} ({STATE['trip']['routeName']}) has reported a breakdown. "
            "The school is coordinating alternative transport. You will be updated shortly."
        ),
        "level": "warning",
        "createdAt": "2026-04-17T13:00:00+05:30",
    })
    return deepcopy(event)


def list_nearby_vehicles() -> list:
    """Return nearby school vehicles that the driver can contact for help (req 12)."""
    return deepcopy(STATE["nearbyVehicles"])


# ── Multi-vehicle helpers (req 13) ───────────────────────────────────────────

def list_driver_vehicles() -> list:
    """Return all vehicles assigned to the current demo driver."""
    return deepcopy(STATE["driverVehicles"])


def switch_active_vehicle(vehicle_id: int) -> dict | None:
    """Set a different vehicle as the driver's active vehicle (req 13).

    Updates the main vehicle, trip, and driver contact records so everything
    in the dashboard reflects the newly selected vehicle.
    """
    target = next((v for v in STATE["driverVehicles"] if v["id"] == vehicle_id), None)
    if not target:
        return None

    # Deactivate all vehicles then activate the selected one
    for v in STATE["driverVehicles"]:
        v["isActive"] = (v["id"] == vehicle_id)

    # Update the top-level vehicle + trip references
    STATE["vehicle"]["id"] = target["id"]
    STATE["vehicle"]["registrationNumber"] = target["registrationNumber"]
    STATE["vehicle"]["label"] = target["label"]
    STATE["vehicle"]["routeName"] = target["routeName"]
    STATE["vehicle"]["capacity"] = target["capacity"]
    STATE["trip"]["busLabel"] = target["label"]
    STATE["trip"]["vehicleLabel"] = target["label"]
    STATE["trip"]["routeName"] = target["routeName"]
    STATE["driverContact"]["vehicleLabel"] = target["label"]
    STATE["driverContact"]["routeName"] = target["routeName"]
    STATE["driverContact"]["phone"] = target["contactPhone"]

    return deepcopy(target)


# ── Driver invite / signup helpers (req 6) ────────────────────────────────────

def validate_driver_invite(token: str) -> dict | None:
    """Return driver invite metadata if the token is valid."""
    invite = STATE["driverInvites"].get(token)
    if not invite or not invite["valid"]:
        return None
    return deepcopy(invite)


def accept_driver_invite(token: str, name: str, phone: str, aadhar: str) -> dict | None:
    """Complete driver signup via an admin invite token (req 6).

    Returns a full login payload immediately — no approval needed for invited drivers.
    """
    invite = STATE["driverInvites"].get(token)
    if not invite or not invite["valid"]:
        return None

    invite["valid"] = False
    STATE["users"]["driver"]["name"] = name
    STATE["users"]["driver"]["aadhar_number"] = aadhar
    STATE["users"]["driver"]["is_pending_approval"] = False

    return {
        "role": "driver",
        "token": "demo-driver-token",
        "name": name,
        "school_slug": invite["school_slug"],
        "is_pending_approval": False,
        "aadhar_number": aadhar,
    }


# ── Dismissal / pickup-intent helpers ────────────────────────────────────────

ETA_LABELS = {0: "Here now", 1: "1 min", 5: "5 min", 10: "10 min"}
VALID_ETAS = {0, 1, 5, 10}


def _dismissal_queue_position(intent_id: int) -> int:
    """Return 1-based queue position among pending intents sorted by (eta, created_at)."""
    pending = [
        i for i in STATE["pickupIntents"]
        if i["status"] in ("pending", "notified")
    ]
    pending.sort(key=lambda x: (x["eta_minutes"], x["created_at"]))
    for pos, intent in enumerate(pending, start=1):
        if intent["id"] == intent_id:
            return pos
    return 0


def signal_arrival(student_id: int, eta_minutes: int) -> dict:
    """Parent signals they are on the way.  Upserts an intent for the student."""
    if eta_minutes not in VALID_ETAS:
        eta_minutes = 5

    # Cancel any existing pending intent for this student
    for intent in STATE["pickupIntents"]:
        if intent["student_id"] == student_id and intent["status"] == "pending":
            intent["status"] = "completed"
            intent["completed_at"] = "2026-04-22T15:00:00+05:30"

    # Find student name from roster
    student = next(
        (s for s in STATE["roster"] if s["id"] == student_id),
        {"fullName": "Student"},
    )
    classroom = next(
        (c for c in STATE["classrooms"] if c["id"] == 1),
        {"label": "Class 4B"},
    )

    new_id = STATE["_dismissal_id_counter"]
    STATE["_dismissal_id_counter"] += 1

    intent = {
        "id": new_id,
        "student_id": student_id,
        "student_name": student["fullName"],
        "parent_name": "Aarav's Parent",
        "classroom": classroom["label"],
        "eta_minutes": eta_minutes,
        "status": "pending",
        "created_at": "2026-04-22T15:00:00+05:30",
        "notified_at": None,
        "completed_at": None,
    }
    STATE["pickupIntents"].append(intent)

    position = _dismissal_queue_position(new_id)
    result = deepcopy(intent)
    result["queue_position"] = position
    result["eta_label"] = ETA_LABELS.get(eta_minutes, f"{eta_minutes} min")
    return result


def get_parent_intent(student_id: int) -> dict | None:
    """Return the active (pending or notified) intent for a student, with queue position."""
    intent = next(
        (i for i in STATE["pickupIntents"]
         if i["student_id"] == student_id and i["status"] in ("pending", "notified")),
        None,
    )
    if not intent:
        return None
    result = deepcopy(intent)
    result["queue_position"] = _dismissal_queue_position(intent["id"])
    result["eta_label"] = ETA_LABELS.get(intent["eta_minutes"], f"{intent['eta_minutes']} min")
    return result


def get_dismissal_queue() -> dict:
    """Return the full live queue for the school dashboard."""
    active = [
        i for i in STATE["pickupIntents"]
        if i["status"] in ("pending", "notified")
    ]
    active.sort(key=lambda x: (x["eta_minutes"], x["created_at"]))

    completed_today = [i for i in STATE["pickupIntents"] if i["status"] == "completed"]

    queue_with_position = []
    for pos, intent in enumerate(active, start=1):
        item = deepcopy(intent)
        item["queue_position"] = pos
        item["eta_label"] = ETA_LABELS.get(intent["eta_minutes"], f"{intent['eta_minutes']} min")
        queue_with_position.append(item)

    total_wait = 0
    notified_count = len([i for i in active if i["status"] == "notified"])
    pending_count = len([i for i in active if i["status"] == "pending"])

    return {
        "queue": queue_with_position,
        "stats": {
            "pending": pending_count,
            "notified": notified_count,
            "completed_today": len(completed_today),
            "avg_wait_minutes": 4,
        },
    }


def mark_child_ready(student_id: int) -> dict | None:
    """School staff marks a child as ready — triggers parent notification."""
    intent = next(
        (i for i in STATE["pickupIntents"]
         if i["student_id"] == student_id and i["status"] == "pending"),
        None,
    )
    if not intent:
        return None

    intent["status"] = "notified"
    intent["notified_at"] = "2026-04-22T15:05:00+05:30"

    # Inject a parent-facing alert so the parent app shows the notification
    STATE["alerts"].insert(0, {
        "id": 500 + student_id,
        "title": f"{intent['student_name']} is at the gate",
        "body": f"Head to the pickup gate — {intent['student_name']} is ready and waiting.",
        "level": "info",
        "createdAt": "2026-04-22T15:05:00+05:30",
    })

    result = deepcopy(intent)
    result["queue_position"] = _dismissal_queue_position(intent["id"])
    result["eta_label"] = ETA_LABELS.get(intent["eta_minutes"], f"{intent['eta_minutes']} min")
    return result


def complete_pickup(student_id: int) -> dict | None:
    """Parent confirms pickup is done — closes the intent."""
    intent = next(
        (i for i in STATE["pickupIntents"]
         if i["student_id"] == student_id and i["status"] in ("pending", "notified")),
        None,
    )
    if not intent:
        return None
    intent["status"] = "completed"
    intent["completed_at"] = "2026-04-22T15:10:00+05:30"
    return deepcopy(intent)


def submit_driver_self_signup(school_slug: str, name: str, phone: str, aadhar: str, vehicle_reg: str) -> dict:
    """Submit a driver self-signup request pending admin approval (req 6).

    The driver app shows a 'Pending Approval' screen until the admin approves
    the request from the school dashboard.
    """
    request_id = len(STATE["driverSignupRequests"]) + 1
    req = {
        "id": request_id,
        "schoolSlug": school_slug,
        "name": name,
        "phone": phone,
        "aadharNumber": aadhar,
        "vehicleReg": vehicle_reg,
        "status": "pending",
        "submittedAt": "2026-04-17T09:00:00+05:30",
    }
    STATE["driverSignupRequests"].append(req)

    # Return a temporary payload with is_pending_approval=True so the app
    # shows the pending approval screen until admin approves.
    return {
        "role": "driver",
        "token": f"demo-pending-{request_id}",
        "name": name,
        "school_slug": school_slug,
        "is_pending_approval": True,
        "signup_request_id": request_id,
    }
