# Generated by Django 5.1.15 on 2026-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_parent__53d0ec_idx',
            old_name='notif_devicetoken_parent_idx',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
