# Generated by Django 5.1.15 on 2026-07-13 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_driverprofile_is_kyc_verified_and_more'),
        ('compliance', '0002_alter_compliancedocument_id_alter_renewalreminder_id'),
        ('tenancy', '0005_tenantconfig_logo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiLockerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('driving_license', 'Driving License'), ('aadhaar', 'Aadhaar')], default='driving_license', max_length=32)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'Awaiting DigiLocker consent'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digilocker_verifications', to='accounts.driverprofile')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_digilocker_verifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
